services:
  react:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      BASE_URL: http://localhost:5173
    ports:
      - "5173:5173"
    entrypoint: /bin/bash -c "npm install && npm run dev -- --host"